# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f3f8064af1959956cabf0692ce568b2726686b853c5f5be1f0757a392a2809f70debcf294a8e594156d0349358200dac5ffb8fc168793aaa064828a8fd3c8369

test:
  secret_key_base: 5518a21b71b94893b7876083273cb4b74ef327cb5962806271b9e9b484d06fb11e69f46501873dfebb3313d308ccb3a6cb17652c79b90b5ae505ca9395f13283

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
